// <auto-generated />
using System;
using JoyDrawBot.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JoyDrawBot.Migrations
{
    [DbContext(typeof(BotDbContext))]
    [Migration("20251124145156_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("joydraw")
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JoyDrawBot.Domain.ContestChannel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ContestEntryId")
                        .HasColumnType("integer")
                        .HasColumnName("contest_entry_id");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("label");

                    b.Property<string>("Url")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_contest_channels");

                    b.HasIndex("ContestEntryId")
                        .HasDatabaseName("ix_contest_channels_contest_entry_id");

                    b.ToTable("contest_channels", "joydraw");
                });

            modelBuilder.Entity("JoyDrawBot.Domain.ContestEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("OriginalText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("original_text");

                    b.Property<DateTimeOffset?>("ReminderSentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reminder_sent_at");

                    b.Property<DateTimeOffset>("ResultsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("results_at");

                    b.Property<long?>("SourceChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("source_chat_id");

                    b.Property<string>("SourceChatTitle")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("source_chat_title");

                    b.Property<string>("SourceChatType")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source_chat_type");

                    b.Property<string>("SourceChatUsername")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_chat_username");

                    b.Property<int?>("SourceMessageId")
                        .HasColumnType("integer")
                        .HasColumnName("source_message_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_contest_entries");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_contest_entries_user_id");

                    b.HasIndex("ResultsAt", "ReminderSentAt")
                        .HasDatabaseName("ix_contest_entries_results_at_reminder_sent_at");

                    b.ToTable("contest_entries", "joydraw");
                });

            modelBuilder.Entity("JoyDrawBot.Domain.UserProfile", b =>
                {
                    b.Property<long>("TelegramId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("FirstName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("last_name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Username")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("username");

                    b.HasKey("TelegramId")
                        .HasName("pk_users");

                    b.ToTable("users", "joydraw");
                });

            modelBuilder.Entity("JoyDrawBot.Domain.ContestChannel", b =>
                {
                    b.HasOne("JoyDrawBot.Domain.ContestEntry", "ContestEntry")
                        .WithMany("Channels")
                        .HasForeignKey("ContestEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contest_channels_contest_entries_contest_entry_id");

                    b.Navigation("ContestEntry");
                });

            modelBuilder.Entity("JoyDrawBot.Domain.ContestEntry", b =>
                {
                    b.HasOne("JoyDrawBot.Domain.UserProfile", "User")
                        .WithMany("ContestEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contest_entries_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JoyDrawBot.Domain.ContestEntry", b =>
                {
                    b.Navigation("Channels");
                });

            modelBuilder.Entity("JoyDrawBot.Domain.UserProfile", b =>
                {
                    b.Navigation("ContestEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
